package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Candidature generated by hbm2java
 */
@Entity
@Table(name="candidature"
    ,schema="public"
)
public class Candidature  implements java.io.Serializable {


     private int id;
     private Niveauqualification niveauqualification;
     private String nom;
     private String prénom;
     private String datenaissance;
     private String adressePostale;
     private String adresseemail;
     private String cv;
     private String datedepot;
     private Set<Secteurcandidat> secteurcandidats = new HashSet<Secteurcandidat>(0);
     private Set<Messageoffredemploi> messageoffredemplois = new HashSet<Messageoffredemploi>(0);
     private Set<Messagecandidature> messagecandidatures = new HashSet<Messagecandidature>(0);

    public Candidature() {
    }

	
    public Candidature(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Candidature(int id, Niveauqualification niveauqualification, String nom, String prénom, String datenaissance, String adressePostale, String adresseemail, String cv, String datedepot, Set<Secteurcandidat> secteurcandidats, Set<Messageoffredemploi> messageoffredemplois, Set<Messagecandidature> messagecandidatures) {
       this.id = id;
       this.niveauqualification = niveauqualification;
       this.nom = nom;
       this.prénom = prénom;
       this.datenaissance = datenaissance;
       this.adressePostale = adressePostale;
       this.adresseemail = adresseemail;
       this.cv = cv;
       this.datedepot = datedepot;
       this.secteurcandidats = secteurcandidats;
       this.messageoffredemplois = messageoffredemplois;
       this.messagecandidatures = messagecandidatures;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idniveauqualif")
    public Niveauqualification getNiveauqualification() {
        return this.niveauqualification;
    }
    
    public void setNiveauqualification(Niveauqualification niveauqualification) {
        this.niveauqualification = niveauqualification;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prénom")
    public String getPrénom() {
        return this.prénom;
    }
    
    public void setPrénom(String prénom) {
        this.prénom = prénom;
    }

    
    @Column(name="datenaissance")
    public String getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(String datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="adresse_postale")
    public String getAdressePostale() {
        return this.adressePostale;
    }
    
    public void setAdressePostale(String adressePostale) {
        this.adressePostale = adressePostale;
    }

    
    @Column(name="adresseemail")
    public String getAdresseemail() {
        return this.adresseemail;
    }
    
    public void setAdresseemail(String adresseemail) {
        this.adresseemail = adresseemail;
    }

    
    @Column(name="cv")
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    
    @Column(name="datedepot")
    public String getDatedepot() {
        return this.datedepot;
    }
    
    public void setDatedepot(String datedepot) {
        this.datedepot = datedepot;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<Secteurcandidat> getSecteurcandidats() {
        return this.secteurcandidats;
    }
    
    public void setSecteurcandidats(Set<Secteurcandidat> secteurcandidats) {
        this.secteurcandidats = secteurcandidats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<Messageoffredemploi> getMessageoffredemplois() {
        return this.messageoffredemplois;
    }
    
    public void setMessageoffredemplois(Set<Messageoffredemploi> messageoffredemplois) {
        this.messageoffredemplois = messageoffredemplois;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<Messagecandidature> getMessagecandidatures() {
        return this.messagecandidatures;
    }
    
    public void setMessagecandidatures(Set<Messagecandidature> messagecandidatures) {
        this.messagecandidatures = messagecandidatures;
    }




}


