package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Messageoffredemploi generated by hbm2java
 */
@Entity
@Table(name="messageoffredemploi"
    ,schema="public"
)
public class Messageoffredemploi  implements java.io.Serializable {


     
     private Candidature candidature;
     private Offresemploi offresemploi;
     private String dateenvoi;
     private String corpsmessage;

    public Messageoffredemploi() {
    }

	
    public Messageoffredemploi(int id, String dateenvoi, String corpsmessage) {
        this.id = id;
        this.dateenvoi = dateenvoi;
        this.corpsmessage = corpsmessage;
    }
    public Messageoffredemploi(int id, Candidature candidature, Offresemploi offresemploi, String dateenvoi, String corpsmessage) {
       this.id = id;
       this.candidature = candidature;
       this.offresemploi = offresemploi;
       this.dateenvoi = dateenvoi;
       this.corpsmessage = corpsmessage;
    }
   
    @Id
    @SequenceGenerator(name="MESSAGEOFFREDEMPLOI_ID_GENERATOR", sequenceName="MESSAGEOFFREDEMPLOI_ID_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MESSAGEOFFREDEMPLOI_ID_GENERATOR")
    private Integer id;

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcandidature")
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idoffreemploi")
    public Offresemploi getOffresemploi() {
        return this.offresemploi;
    }
    
    public void setOffresemploi(Offresemploi offresemploi) {
        this.offresemploi = offresemploi;
    }

    
    @Column(name="dateenvoi", nullable=false, length=50)
    public String getDateenvoi() {
        return this.dateenvoi;
    }
    
    public void setDateenvoi(String dateenvoi) {
        this.dateenvoi = dateenvoi;
    }

    
    @Column(name="corpsmessage", nullable=false, length=50)
    public String getCorpsmessage() {
        return this.corpsmessage;
    }
    
    public void setCorpsmessage(String corpsmessage) {
        this.corpsmessage = corpsmessage;
    }




}


