package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Niveauqualification generated by hbm2java
 */
@Entity
@Table(name="niveauqualification"
    ,schema="public"
)
public class Niveauqualification  implements java.io.Serializable {


     private String intitule;
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);
     private Set<Offresemploi> offresemplois = new HashSet<Offresemploi>(0);

    public Niveauqualification() {
    }

	
    public Niveauqualification(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public Niveauqualification(int id, String intitule, Set<Candidature> candidatures, Set<Offresemploi> offresemplois) {
       this.id = id;
       this.intitule = intitule;
       this.candidatures = candidatures;
       this.offresemplois = offresemplois;
    }
   
    @Id
    @SequenceGenerator(name="NIVEAUQUALIFICATION_ID_GENERATOR", sequenceName="NIVEAUQUALIFICATION_ID_SEQ", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="NIVEAUQUALIFICATION_ID_GENERATOR")
    private Integer id;
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauqualification")
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="niveauqualification")
    public Set<Offresemploi> getOffresemplois() {
        return this.offresemplois;
    }
    
    public void setOffresemplois(Set<Offresemploi> offresemplois) {
        this.offresemplois = offresemplois;
    }




}


