package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Offresemploi generated by hbm2java
 */
@Entity
@Table(name="offresemploi"
    ,schema="public"
)
public class Offresemploi  implements java.io.Serializable {


     private int id;
     private Niveauqualification niveauqualification;
     private String titre;
     private String descriptifmission;
     private String datedepot;
     private String profilrecherche;
     private Integer identreprise;
     private Set<Secteuroffre> secteuroffres = new HashSet<Secteuroffre>(0);
     private Set<Messagecandidature> messagecandidatures = new HashSet<Messagecandidature>(0);
     private Set<Messageoffredemploi> messageoffredemplois = new HashSet<Messageoffredemploi>(0);

    public Offresemploi() {
    }

	
    public Offresemploi(int id, String descriptifmission) {
        this.id = id;
        this.descriptifmission = descriptifmission;
    }
    public Offresemploi(int id, Niveauqualification niveauqualification, String titre, String descriptifmission, String datedepot, String profilrecherche, Integer identreprise, Set<Secteuroffre> secteuroffres, Set<Messagecandidature> messagecandidatures, Set<Messageoffredemploi> messageoffredemplois) {
       this.id = id;
       this.niveauqualification = niveauqualification;
       this.titre = titre;
       this.descriptifmission = descriptifmission;
       this.datedepot = datedepot;
       this.profilrecherche = profilrecherche;
       this.identreprise = identreprise;
       this.secteuroffres = secteuroffres;
       this.messagecandidatures = messagecandidatures;
       this.messageoffredemplois = messageoffredemplois;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idniveauqualif")
    public Niveauqualification getNiveauqualification() {
        return this.niveauqualification;
    }
    
    public void setNiveauqualification(Niveauqualification niveauqualification) {
        this.niveauqualification = niveauqualification;
    }

    
    @Column(name="titre")
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="descriptifmission", nullable=false, length=50)
    public String getDescriptifmission() {
        return this.descriptifmission;
    }
    
    public void setDescriptifmission(String descriptifmission) {
        this.descriptifmission = descriptifmission;
    }

    
    @Column(name="datedepot", length=30)
    public String getDatedepot() {
        return this.datedepot;
    }
    
    public void setDatedepot(String datedepot) {
        this.datedepot = datedepot;
    }

    
    @Column(name="profilrecherche")
    public String getProfilrecherche() {
        return this.profilrecherche;
    }
    
    public void setProfilrecherche(String profilrecherche) {
        this.profilrecherche = profilrecherche;
    }

    
    @Column(name="identreprise")
    public Integer getIdentreprise() {
        return this.identreprise;
    }
    
    public void setIdentreprise(Integer identreprise) {
        this.identreprise = identreprise;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offresemploi")
    public Set<Secteuroffre> getSecteuroffres() {
        return this.secteuroffres;
    }
    
    public void setSecteuroffres(Set<Secteuroffre> secteuroffres) {
        this.secteuroffres = secteuroffres;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offresemploi")
    public Set<Messagecandidature> getMessagecandidatures() {
        return this.messagecandidatures;
    }
    
    public void setMessagecandidatures(Set<Messagecandidature> messagecandidatures) {
        this.messagecandidatures = messagecandidatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offresemploi")
    public Set<Messageoffredemploi> getMessageoffredemplois() {
        return this.messageoffredemplois;
    }
    
    public void setMessageoffredemplois(Set<Messageoffredemploi> messageoffredemplois) {
        this.messageoffredemplois = messageoffredemplois;
    }




}


