package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Secteuroffre generated by hbm2java
 */
@Entity
@Table(name="secteuroffre"
    ,schema="public"
)
public class Secteuroffre  implements java.io.Serializable {


     private SecteuroffreId id;
     private Offresemploi offresemploi;
     private Secteuractivite secteuractivite;
     private Integer nombredesecteurs;

    public Secteuroffre() {
    }

	
    public Secteuroffre(SecteuroffreId id, Offresemploi offresemploi, Secteuractivite secteuractivite) {
        this.id = id;
        this.offresemploi = offresemploi;
        this.secteuractivite = secteuractivite;
    }
    public Secteuroffre(SecteuroffreId id, Offresemploi offresemploi, Secteuractivite secteuractivite, Integer nombredesecteurs) {
       this.id = id;
       this.offresemploi = offresemploi;
       this.secteuractivite = secteuractivite;
       this.nombredesecteurs = nombredesecteurs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idoffreemploi", column=@Column(name="idoffreemploi", nullable=false) ), 
        @AttributeOverride(name="idsecteuractivite", column=@Column(name="idsecteuractivite", nullable=false) ) } )
    public SecteuroffreId getId() {
        return this.id;
    }
    
    public void setId(SecteuroffreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idoffreemploi", nullable=false, insertable=false, updatable=false)
    public Offresemploi getOffresemploi() {
        return this.offresemploi;
    }
    
    public void setOffresemploi(Offresemploi offresemploi) {
        this.offresemploi = offresemploi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsecteuractivite", nullable=false, insertable=false, updatable=false)
    public Secteuractivite getSecteuractivite() {
        return this.secteuractivite;
    }
    
    public void setSecteuractivite(Secteuractivite secteuractivite) {
        this.secteuractivite = secteuractivite;
    }

    
    @Column(name="nombredesecteurs")
    public Integer getNombredesecteurs() {
        return this.nombredesecteurs;
    }
    
    public void setNombredesecteurs(Integer nombredesecteurs) {
        this.nombredesecteurs = nombredesecteurs;
    }




}


