package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SecteurcandidatId generated by hbm2java
 */
@Embeddable
public class SecteurcandidatId  implements java.io.Serializable {


     private int idsecteuractivite;
     private int idcandidature;

    public SecteurcandidatId() {
    }

    public SecteurcandidatId(int idsecteuractivite, int idcandidature) {
       this.idsecteuractivite = idsecteuractivite;
       this.idcandidature = idcandidature;
    }
   


    @Column(name="idsecteuractivite", nullable=false)
    public int getIdsecteuractivite() {
        return this.idsecteuractivite;
    }
    
    public void setIdsecteuractivite(int idsecteuractivite) {
        this.idsecteuractivite = idsecteuractivite;
    }


    @Column(name="idcandidature", nullable=false)
    public int getIdcandidature() {
        return this.idcandidature;
    }
    
    public void setIdcandidature(int idcandidature) {
        this.idcandidature = idcandidature;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SecteurcandidatId) ) return false;
		 SecteurcandidatId castOther = ( SecteurcandidatId ) other; 
         
		 return (this.getIdsecteuractivite()==castOther.getIdsecteuractivite())
 && (this.getIdcandidature()==castOther.getIdcandidature());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdsecteuractivite();
         result = 37 * result + this.getIdcandidature();
         return result;
   }   


}


