package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Secteuractivite generated by hbm2java
 */
@Entity
@Table(name="secteuractivite"
    ,schema="public"
)
public class Secteuractivite  implements java.io.Serializable {


     private int id;
     private String intitule;
     private Set<Secteuroffre> secteuroffres = new HashSet<Secteuroffre>(0);
     private Set<Secteurcandidat> secteurcandidats = new HashSet<Secteurcandidat>(0);

    public Secteuractivite() {
    }

	
    public Secteuractivite(int id, String intitule) {
        this.id = id;
        this.intitule = intitule;
    }
    public Secteuractivite(int id, String intitule, Set<Secteuroffre> secteuroffres, Set<Secteurcandidat> secteurcandidats) {
       this.id = id;
       this.intitule = intitule;
       this.secteuroffres = secteuroffres;
       this.secteurcandidats = secteurcandidats;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="intitule", nullable=false, length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="secteuractivite")
    public Set<Secteuroffre> getSecteuroffres() {
        return this.secteuroffres;
    }
    
    public void setSecteuroffres(Set<Secteuroffre> secteuroffres) {
        this.secteuroffres = secteuroffres;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="secteuractivite")
    public Set<Secteurcandidat> getSecteurcandidats() {
        return this.secteurcandidats;
    }
    
    public void setSecteurcandidats(Set<Secteurcandidat> secteurcandidats) {
        this.secteurcandidats = secteurcandidats;
    }




}


