package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SecteuroffreId generated by hbm2java
 */
@Embeddable
public class SecteuroffreId  implements java.io.Serializable {


     private int idoffreemploi;
     private int idsecteuractivite;

    public SecteuroffreId() {
    }

    public SecteuroffreId(int idoffreemploi, int idsecteuractivite) {
       this.idoffreemploi = idoffreemploi;
       this.idsecteuractivite = idsecteuractivite;
    }
   


    @Column(name="idoffreemploi", nullable=false)
    public int getIdoffreemploi() {
        return this.idoffreemploi;
    }
    
    public void setIdoffreemploi(int idoffreemploi) {
        this.idoffreemploi = idoffreemploi;
    }


    @Column(name="idsecteuractivite", nullable=false)
    public int getIdsecteuractivite() {
        return this.idsecteuractivite;
    }
    
    public void setIdsecteuractivite(int idsecteuractivite) {
        this.idsecteuractivite = idsecteuractivite;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SecteuroffreId) ) return false;
		 SecteuroffreId castOther = ( SecteuroffreId ) other; 
         
		 return (this.getIdoffreemploi()==castOther.getIdoffreemploi())
 && (this.getIdsecteuractivite()==castOther.getIdsecteuractivite());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdoffreemploi();
         result = 37 * result + this.getIdsecteuractivite();
         return result;
   }   


}


