package eu.telecom_bretagne.cabinet_recrutement.data.model;
// Generated Feb 7, 2023, 10:29:19 AM by Hibernate Tools 5.4.20.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Secteurcandidat generated by hbm2java
 */
@Entity
@Table(name="secteurcandidat"
    ,schema="public"
)
public class Secteurcandidat  implements java.io.Serializable {


     private SecteurcandidatId id;
     private Candidature candidature;
     private Secteuractivite secteuractivite;
     private Integer nombredecandidats;

    public Secteurcandidat() {
    }

	
    public Secteurcandidat(SecteurcandidatId id, Candidature candidature, Secteuractivite secteuractivite) {
        this.id = id;
        this.candidature = candidature;
        this.secteuractivite = secteuractivite;
    }
    public Secteurcandidat(SecteurcandidatId id, Candidature candidature, Secteuractivite secteuractivite, Integer nombredecandidats) {
       this.id = id;
       this.candidature = candidature;
       this.secteuractivite = secteuractivite;
       this.nombredecandidats = nombredecandidats;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idsecteuractivite", column=@Column(name="idsecteuractivite", nullable=false) ), 
        @AttributeOverride(name="idcandidature", column=@Column(name="idcandidature", nullable=false) ) } )
    public SecteurcandidatId getId() {
        return this.id;
    }
    
    public void setId(SecteurcandidatId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcandidature", nullable=false, insertable=false, updatable=false)
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsecteuractivite", nullable=false, insertable=false, updatable=false)
    public Secteuractivite getSecteuractivite() {
        return this.secteuractivite;
    }
    
    public void setSecteuractivite(Secteuractivite secteuractivite) {
        this.secteuractivite = secteuractivite;
    }

    
    @Column(name="nombredecandidats")
    public Integer getNombredecandidats() {
        return this.nombredecandidats;
    }
    
    public void setNombredecandidats(Integer nombredecandidats) {
        this.nombredecandidats = nombredecandidats;
    }




}


